In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
from google.colab  import files
uploaded=files.upload()

Saving 50_Startups.csv to 50_Startups.csv


In [3]:
df=pd.read_csv('50_Startups.csv')

In [6]:
df=df.rename({'R&D Spend':'rnd',	'Administration':'admin',	'Marketing Spend':'market','State':'state',	'Profit':'profit'},axis=1)

In [24]:
X=df[['rnd','admin','market',]]

In [25]:
y=df[['profit']]

In [26]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.3)

In [27]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()


In [28]:
X_train[['rnd','admin','market']]=scaler.fit_transform(X_train[['rnd','admin','market']])

In [29]:
X_test[['rnd','admin','market']]=scaler.fit_transform(X_test[['rnd','admin','market']])

In [30]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [32]:
model.intercept_

array([105495.27914286])

In [33]:
model.coef_

array([[37573.53595788,  -746.75877936,  4259.96305564]])

In [34]:
y_pred_test=model.predict(X_test)
y_pred_test

array([[104904.12940854],
       [169661.31275717],
       [106949.52325861],
       [ 83155.80679507],
       [130468.39915187],
       [ 63112.32631346],
       [114941.75903402],
       [ 79477.36042856],
       [196629.62437252],
       [ 88035.39398685],
       [ 61001.62206697],
       [167330.76206533],
       [ 83116.3574092 ],
       [ 66781.4114966 ],
       [ 66863.39859809]])

In [35]:
y_pred_train=model.predict(X_train)
y_pred_train

array([[ 70727.91703869],
       [161089.84679889],
       [ 90463.25450264],
       [118800.1084028 ],
       [ 71247.3835333 ],
       [ 99037.83962895],
       [ 91429.00276936],
       [ 84433.87988242],
       [183748.94247972],
       [136251.18880681],
       [ 48118.28507969],
       [118120.78430567],
       [ 45949.28164172],
       [155837.10645522],
       [ 76393.43096466],
       [102267.30353975],
       [150077.63066369],
       [ 47111.44886082],
       [129915.63439912],
       [ 75635.49169502],
       [118034.37066718],
       [ 98811.83004688],
       [ 90032.6505948 ],
       [165001.42973299],
       [116266.41978684],
       [152811.03241085],
       [111644.85636406],
       [ 58571.41039718],
       [ 48590.63919856],
       [ 75536.44864035],
       [ 64083.06613994],
       [128320.45584648],
       [191022.9013127 ],
       [157167.87713436],
       [ 59783.62027789]])

In [37]:
from sklearn.metrics import r2_score

In [39]:
r2_train=r2_score(y_train,y_pred_train)
r2_test=r2_score(y_test,y_pred_test)
print(r2_train,r2_test)

0.9485173053110522 0.2703685876769468
